# Generated by Django 4.1.2 on 2022-11-12 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('host_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=4)),
                ('mac_address', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('os', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('dns', models.CharField(max_length=25)),
                ('get_way', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('network_card_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('state', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='core.host')),
            ],
        ),
        migrations.CreateModel(
            name='FireWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('default_allow_policy', models.BooleanField(default=False)),
                ('default_deny_policy', models.BooleanField(default=False)),
                ('reset', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('allowed_port', models.ManyToManyField(blank=True, null=True, related_name='allowed', to='core.port')),
                ('denied_port', models.ManyToManyField(blank=True, null=True, related_name='denied', to='core.port')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firewall', to='core.host')),
                ('limited_port', models.ManyToManyField(blank=True, null=True, related_name='limited', to='core.port')),
            ],
        ),
    ]
