# Generated by Django 4.1.2 on 2022-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='host',
        ),
        migrations.AddField(
            model_name='port',
            name='host',
            field=models.ManyToManyField(related_name='ports', to='core.host'),
        ),
    ]
