# Generated by Django 4.1.2 on 2022-10-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_devices_ports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='ports',
        ),
        migrations.AddField(
            model_name='ports',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='core.devices'),
            preserve_default=False,
        ),
    ]
