# Generated by Django 4.1.2 on 2022-11-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_host_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='dns',
            field=models.CharField(default='4.2.2.4', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='get_way',
            field=models.GenericIPAddressField(default='192.168.1.1'),
            preserve_default=False,
        ),
    ]
