# Generated by Django 4.1.1 on 2022-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_machineipaddress_deviceipaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceipaddress',
            old_name='ip',
            new_name='ip_address',
        ),
        migrations.AddField(
            model_name='deviceipaddress',
            name='host_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceipaddress',
            name='status',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
