# Generated by Django 4.1.2 on 2022-10-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_devices_ports_ports_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ports',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
