# Generated by Django 4.1.2 on 2022-11-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_host_dns_host_get_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='network_card_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
