# Generated by Django 4.1.1 on 2022-09-25 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_ip_deviceipaddress_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceipaddress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
