# Generated by Django 4.1.2 on 2022-10-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deviceipaddress_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('host_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=4)),
                ('mac_address', models.CharField(max_length=20)),
                ('vendor', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceIpAddress',
        ),
    ]
