# Generated by Django 4.1.2 on 2022-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_port_host_port_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
