# Generated by Django 4.1.2 on 2022-10-29 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ports_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ports',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ports',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
