# Generated by Django 4.1.2 on 2022-10-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_devices_delete_deviceipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='mac_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
