# Generated by Django 4.1.2 on 2022-11-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_firewall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewall',
            name='allowed_port',
        ),
        migrations.RemoveField(
            model_name='firewall',
            name='denied_port',
        ),
        migrations.RemoveField(
            model_name='firewall',
            name='limited_port',
        ),
        migrations.AddField(
            model_name='firewall',
            name='allowed_port',
            field=models.ManyToManyField(blank=True, null=True, related_name='allowed', to='core.port'),
        ),
        migrations.AddField(
            model_name='firewall',
            name='denied_port',
            field=models.ManyToManyField(blank=True, null=True, related_name='denied', to='core.port'),
        ),
        migrations.AddField(
            model_name='firewall',
            name='limited_port',
            field=models.ManyToManyField(blank=True, null=True, related_name='limited', to='core.port'),
        ),
    ]
