# Generated by Django 4.1.2 on 2022-11-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_firewall_allowed_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='default_allow_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firewall',
            name='default_deny_policy',
            field=models.BooleanField(default=False),
        ),
    ]
